---
name: Setup
description: Setup Python and install dependencies.

inputs:
  python_version:
    description: The Python version.
    required: false
    default: '3.14'
  just_version:
    description: The just version.
    required: false
    default: '1.57.0'
  install_dependencies:
    description: Install dependencies.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup just
      uses: extractions/setup-just@v4
      with:
        just-version: ${{ inputs.just_version }}
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python_version }}
        enable-cache: true
    - name: Check lockfile
      if: inputs.install_dependencies == 'true'
      shell: bash
      run: uv lock --check
    - name: Install dependencies
      if: inputs.install_dependencies == 'true'
      shell: bash
      run: uv sync
