---
name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test (Python ${{ matrix.python }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        include:
          - os: ubuntu-latest
            os_name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python }}
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Test
        run: make test
  lint:
    name: Lint (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: ${{ matrix.python }}
      - name: Lint
        run: make lint
  build:
    name: Build (Python ${{ matrix.python }} on ${{ matrix.os_name }})
    uses: ./.github/workflows/_build.yml
    with:
      python_version: ${{ matrix.python }}
      runs_on: ${{ matrix.os }}
      upload_artifact: ${{ matrix.python == '3.11' && matrix.os == 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        include:
          - os: ubuntu-latest
            os_name: Linux
  install:
    name: Install (Python ${{ matrix.python }} on ${{ matrix.os_name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        include:
          - os: ubuntu-latest
            os_name: Linux
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: .
      - name: Find wheels
        uses: tj-actions/glob@v21
        id: wheels
        with:
          files: '*.whl'
      - name: Install
        run: pip install ${{ steps.wheels.outputs.paths }}
      - name: Create main.py
        uses: DamianReeves/write-file-action@v1.3
        with:
          write-mode: overwrite
          path: main.py
          contents: |
            import seam
      - name: Run
        run: python main.py
